Repository koekalenteri/koekalenteri, pull requests merged in 2021-04, with the labels that each got.

#2 Continuous Integration
  .github/workflows/ci.yml
Labels: infrastructure

#3 Coveralls
  .github/workflows/ci.yml
  src/koekalenteri-frontend/package.json
Labels: infrastructure

#5 Add lint step to CI, require indent of 2 spaces
  .github/workflows/ci.yml
  src/koekalenteri-frontend/README.md
  src/koekalenteri-frontend/package.json
  src/koekalenteri-frontend/src/components/TestList/index.tsx
  src/koekalenteri-frontend/src/stores/TestStore.ts
Labels: infrastructure

#4 Add generics about frontend in readme
  README.md
  src/koekalenteri-frontend/README.md
Labels: documentation

#6 Front end aole first try
  src/koekalenteri-frontend/package-lock.json
  src/koekalenteri-frontend/package.json
  src/koekalenteri-frontend/src/App.test.tsx
  src/koekalenteri-frontend/src/App.tsx
  src/koekalenteri-frontend/src/assets/Theme.ts
  src/koekalenteri-frontend/src/assets/snj-logo.jpeg
  src/koekalenteri-frontend/src/components/EventText.tsx
  src/koekalenteri-frontend/src/index.tsx
  src/koekalenteri-frontend/src/layout/Header.tsx
  src/koekalenteri-frontend/src/layout/InfoContainer.tsx
  src/koekalenteri-frontend/src/layout/MainContainer.tsx
  src/koekalenteri-frontend/src/layout/NotificationContainer.tsx
  src/koekalenteri-frontend/src/pages/SearchPage.tsx
Labels: enhancement
